services:
  mysql:
    image: mysql:8.0
    container_name: food_delivery_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_delivery
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
